### ISSUE TITLE
Interop with go

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-bitswap#36]
Documenting things here.

**Comment by dignifiedquire** [comment]
(Using 
Something is up with `multistream`

- Even though @whyrusleeping said go-ipfs supports `/ipfs/bitswap/1.0.0` I had the protocol to`/ipfs/bitswap` to receive the connections made from go-ipfs.
- When that happens I get the below output as debug. 

```
libp2p:swarm:dial dialing QmPZBs5MenpXaBJRhiUq4nsPVqAH6aqTCapYRjESXYrggQ +5s
  multistream:dialer (24wzue) dialer handle conn +1ms
  multistream:agreement (24wzue) writing multicodec /multistream/1.0.0 +0ms
  multistream:agreement (24wzue) received ack: /multistream/1.0.0 +4ms
  multistream:dialer (24wzue) handshake success +0ms
  multistream:dialer (24wzue) dialer select /ipfs/bitswap +0ms
  multistream:agreement (24wzue) writing multicodec /ipfs/bitswap +1ms
  multistream:agreement:error Error: pull-reader: read exceeded timeout
    at Timeout._onTimeout (/Users/dignifiedquire/opensource/ipfs/js-ipfs/node_modules/pull-reader/index.js:16:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5) +55s
  multistream:listener adding handler: /spdy/3.1.0 +11ms
  multistream:listener adding handler: /ipfs/id/1.0.0 +0ms
  multistream:listener adding handler: /secio/1.0.0 +1ms
  multistream:listener adding handler: /ipfs/bitswap +0ms
  multistream:listener (9n8b2g) listener handle conn +0ms
  multistream:agreement (9n8b2g) writing multicodec /multistream/1.0.0 +0ms
  bitswap:network dialed QmPZBs5MenpXaBJRhiUq4nsPVqAH6aqTCapYRjESXYrggQ +1m Error: pull-reader: read exceeded timeout
    at Timeout._onTimeout (/Users/dignifiedquire/opensource/ipfs/js-ipfs/node_modules/pull-reader/index.js:16:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
  bitswap:wantmanager:queue:error send error: pull-reader: read exceeded timeout +0ms
  multistream:listener adding handler: /spdy/3.1.0 +1m
  multistream:listener adding handler: /ipfs/id/1.0.0 +0ms
  multistream:listener adding handler: /secio/1.0.0 +0ms
  multistream:listener adding handler: /ipfs/bitswap +0ms
  multistream:listener (b8vw6h) listener handle conn +0ms
  multistream:agreement (b8vw6h) writing multicodec /multistream/1.0.0 +0ms
```

So the current issues seem to be with multistream, such that that bitswap isn't even able to receive messages properly.

**Comment by dignifiedquire** [comment]
Restarted daemon, now working with https://github.com/ipfs/js-ipfs-bitswap/pull/37

**Comment by dignifiedquire** [comment]
Also needs https://github.com/ipfs/js-ipfs/pull/481
